apiVersion: v1
kind: Pod
metadata:
  name: static-web-pod
  labels:
    app: static-web
spec:
  containers:
  - name: static-web
    image: web-site:latest        # Your local Docker image
    imagePullPolicy: Never
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  type: NodePort
  selector:
    app: static-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
